version: '3.8'

services:
  # --- Serviço 1: Banco de Dados (PostgreSQL) ---
  postgres:
    image: postgres:15-alpine
    container_name: logistica-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=logistica_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - logistica-network

  # --- Serviço 2: Mensageria (RabbitMQ) ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: logistica-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - logistica-network

  # --- Serviço 3: Zookeeper (Gerente do Kafka) ---
  zookeeper:
    # MUDANÇA AQUI: Fixamos a versão 7.4.0 para evitar erros do "latest"
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: logistica-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - logistica-network

  # --- Serviço 4: Kafka (Streaming) ---
  kafka:
    # MUDANÇA AQUI: Fixamos a versão 7.4.0 compatível com Zookeeper
    image: confluentinc/cp-kafka:7.4.0
    container_name: logistica-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Configurações de Rede
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - logistica-network

volumes:
  postgres-data:

networks:
  logistica-network:
    driver: bridge